import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import Banner from "../components/Banner";
import About from "../components/About";
import Jobs from "../components/Jobs";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className="tw-w-full tw-bg-darkGray tw-flex tw-flex-col tw-items-center">
      <Head>
        <title>Devium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Banner />
        <About />
        <Jobs />
        <Contact />
      </Layout>
    </div>
  );
}
